(require 'key-chord)
(key-chord-mode 1)
(key-chord-define-global "uu" 'undo)
(key-chord-define-global "UU" 'undo-tree-visualize)
(key-chord-define-global "jj" 'avy-goto-char)
(key-chord-define-global "jk" 'avy-goto-char-2)
(key-chord-define-global "jl" 'avy-goto-line)
(key-chord-define-global "mm" 'set-mark-command)
(key-chord-define-global "aw" 'ace-window)
(key-chord-define-global "bb" 'switch-to-buffer)
(key-chord-define-global "BB" 'buffer-menu-other-window)
(key-chord-define-global "JJ" 'join-line)
(key-chord-define-global "))" 'forward-list)
(key-chord-define-global "((" 'backward-list)
(key-chord-define-global "__" 'backward-up-list)
(key-chord-define-global "||" 'indent-region)
